### ISSUE TITLE
RSS points to a wrong image

### ISSUE THREAD

**Issue by Thanatermesis** [HEIGE-PCloud/DoIt#653] opened 2022-07-08 17:59 UTC
### Describe the bug 描述你遇到的错误

In my blog: https://blog.thanatermesis.org the images are rendering correctly (correct link path's), but seems like the RSS feed points to a wrong image link, as we can see here:  https://blog.thanatermesis.org/en/index.xml  (search for keyword personality-empty.jpg ), so it points to / instead of the sub-url article directory

Thank you

**Comment by CXwudi** [comment] 2022-07-28 20:21
I can confirm this issue too:

This is what my sample test blog post looks like:
![image](https://user-images.githubusercontent.com/17377423/181629495-896e9b23-971e-40ea-95ca-a73355517ba6.png)

And when I subscribe to the RSS feed of my test blog, this is what it looks like in the RSS feed reader:
![image](https://user-images.githubusercontent.com/17377423/181629863-abebc634-2ec8-4436-8387-b72e7e74c69b.png)

We can see that the image is missing in the RSS feed reader

**Comment by HEIGE-PCloud** [comment] 2022-08-11 15:19
fixed in https://github.com/HEIGE-PCloud/DoIt/commit/9beae116d0fbd62de241568e956b274f5e164d0c

**Closed as completed by HEIGE-PCloud** 2022-08-11 15:19 UTC
Labels: bug
