### ISSUE TITLE
[BUG] Build Failure on Example Site

### ISSUE THREAD

**Issue by ChatGPT2** [HEIGE-PCloud/DoIt#864] opened 2023-02-11 01:36 UTC
### Describe the bug 描述你遇到的错误

fatal error: pipe failed

goroutine 1 [running]:
runtime.throw({0x101d91db1?, 0xc008e43950?})
	runtime/panic.go:1047 +0x5d fp=0xc000b777e0 sp=0xc000b777b0 pc=0x10003af7d
runtime.sigNoteSetup(0x10001631c)
	runtime/os_darwin.go:101 +0xc5 fp=0xc000b77808 sp=0xc000b777e0 pc=0x100037f05
os/signal.signal_enable(0x2)
	runtime/sigqueue.go:205 +0x39 fp=0xc000b77828 sp=0xc000b77808 pc=0x10006b639
os/signal.enableSignal(...)
	os/signal/signal_unix.go:49
os/signal.Notify.func1(0x101afa540?)
	os/signal/signal.go:145 +0x73 fp=0xc000b77850 sp=0xc000b77828 pc=0x10171b093
os/signal.Notify(0xc00840e3c0, {0xc000b77af8, 0x2, 0x0?})
	os/signal/signal.go:165 +0x1ff fp=0xc000b778c8 sp=0xc000b77850 pc=0x10171af5f
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc000698700, 0xc000693280)
	github.com/gohugoio/hugo/commands/server.go:593 +0x50c fp=0xc000b77b30 sp=0xc000b778c8 pc=0x10175044c
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000693280, 0xc0000e1800, {0x0?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/server.go:297 +0x3c8 fp=0xc000b77c78 sp=0xc000b77b30 pc=0x10174c608
github.com/gohugoio/hugo/commands.(*commandsBuilder).newServerCmdSignaled.func1(0xc0000e1800?, {0xc00059e100?, 0x2?, 0x2?})
	github.com/gohugoio/hugo/commands/server.go:96 +0x36 fp=0xc000b77cc8 sp=0xc000b77c78 pc=0x10174c0d6
github.com/spf13/cobra.(*Command).execute(0xc0000e1800, {0xc00059e020, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862 fp=0xc000b77e00 sp=0xc000b77cc8 pc=0x1005b90c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000494000)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd fp=0xc000b77eb8 sp=0xc000b77e00 pc=0x1005b993d
github.com/gohugoio/hugo/commands.Execute({0xc0001b2010, 0x3, 0x3})
	github.com/gohugoio/hugo/commands/hugo.go:92 +0xbd fp=0xc000b77f38 sp=0xc000b77eb8 pc=0x1017383bd
main.main()
	github.com/gohugoio/hugo/main.go:23 +0x56 fp=0xc000b77f80 sp=0xc000b77f38 pc=0x101756076
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc000b77fe0 sp=0xc000b77f80 pc=0x10003d792
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000b77fe8 sp=0xc000b77fe0 pc=0x10006f901

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00008afb0 sp=0xc00008af90 pc=0x10003db56
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.forcegchelper()
	runtime/proc.go:302 +0xad fp=0xc00008afe0 sp=0xc00008afb0 pc=0x10003d9ed
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00008afe8 sp=0xc00008afe0 pc=0x10006f901
created by runtime.init.6
	runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00008b790 sp=0xc00008b770 pc=0x10003db56
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:297 +0xd7 fp=0xc00008b7c8 sp=0xc00008b790 pc=0x100028db7
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc00008b7e0 sp=0xc00008b7c8 pc=0x10001da26
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00008b7e8 sp=0xc00008b7e0 pc=0x10006f901
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

**Comment by HEIGE-PCloud** [comment] 2023-02-11 02:05
We temporarily close this due to the lack of enough information.
Please provide a minimal reproduction to reopen the issue.
Thanks.

**Closed as not planned by HEIGE-PCloud** 2023-02-11 02:05 UTC
Labels: bug
