### ISSUE TITLE
[BUG] 文章发布日期与修改日期一致，文章就不显示了~~~

### ISSUE THREAD

**Issue by al6nlee** [HEIGE-PCloud/DoIt#1257] opened 2024-04-27 07:55 UTC

**Comment by HEIGE-PCloud** [comment] 2024-04-27 08:34
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed as completed by HEIGE-PCloud** 2024-04-27 08:34 UTC
Labels: invalid

**Comment by al6nlee** [comment] 2024-04-27 09:45
<img width="667" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/89306357/702d41b6-7fe6-43be-a741-27b39c05e390">
<img width="1007" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/89306357/559d752a-34c1-4819-968f-199476a8a789">


look，if CreateDate equ ModDate，The blog is no longer displayed.

**Comment by al6nlee** [comment] 2024-04-27 09:46
<img width="1142" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/89306357/d4919930-4cc8-4642-b318-707dfc32d1bf">

**Comment by al6nlee** [comment] 2024-04-27 09:49
@HEIGE-PCloud

**Comment by HEIGE-PCloud** [comment] 2024-04-27 10:54
Incorrect date format. See examples at https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/posts/theme-documentation-basics/index.en.md?plain=1

```
date: 2020-03-03T21:29:01+08:00
lastmod: 2020-03-06T21:29:01+08:00
```

Reference https://gohugo.io/methods/page/date/

**Comment by al6nlee** [comment] 2024-04-27 11:16
ohhhhhhh    thanks~~     successful!
