### ISSUE TITLE
[BUG] Error: Error building site: failed to render pages: render of "page" failed

### ISSUE THREAD

**Issue by zhaoyiluo** [HEIGE-PCloud/DoIt#124] opened 2021-07-03 16:20 UTC
### Describe the bug 

I was trying to build the example website. I created a new site, cloned the repo, and copied everything from `E:\IMZLUO\themes\DoIt\exampleSite` to `E:\IMZLUO\`.

### Expected behavior

The example site should have been built successfully.

### Screenshots

```
E:\IMZLUO>hugo serve --disableFastRender
Start building sites …
hugo v0.84.4-020E4ACE+extended windows/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
WARN 2021/07/04 00:09:35

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.
Built in 30626 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:122:124: executing "content" at <partial "function/content.html">: error calling partial: "E:\IMZLUO\themes\DoIt\layouts\partials\function\content.html:6:23": execute of template failed: template: partials/function/content.html:6:23: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.
```

### Build Environment

- OS: Windows 10
- Theme version/commit: [ee866f9](https://github.com/HEIGE-PCloud/DoIt/commit/ee866f94c1312625cd55eb31b2ed456bdc60caa5)
- Hugo version: v0.84.4-020E4ACE+extended

### Preview Environment

N/A

### Additional Information

N/A

**Comment by HEIGE-PCloud** [comment] 2021-07-04 01:11
If you want to build the exampleSite, you don't need to copy anything. Under `IMZLUO` folder, run `hugo server --source=themes\DoIt\exampleSite --disableFastRender`. (https://github.com/HEIGE-PCloud/DoIt#documentation)

You can also build the exampleSite with `npm run serve` under `DoIt` folder. For more information, check out [CONTRIBUTING.md](https://github.com/HEIGE-PCloud/DoIt/blob/main/CONTRIBUTING.md).

**Comment by zhaoyiluo** [comment] 2021-07-04 07:31
Hi @HEIGE-PCloud , the solution you suggested also triggered the same problem.

I would say that these two solutions of running the example site are almost the same but via two different approaches.

Would appreciate seeing if this issue could be reproduced on your side.  I reproduced it both on my personal laptop and company computer.

Thanks.

```
Zhaoyi Luo@ZHAOYILUO-NB1 MINGW64 /e/IMZLUO
$ hugo server --source=themes/DoIt/exampleSite --disableFastRender
Start building sites …
hugo v0.84.4-020E4ACE+extended windows/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
WARN 2021/07/04 15:25:19

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
Built in 30672 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:144:124: executing "content" at <partial "function/content.html">: error calling partial: "E:\IMZLUO\themes\DoIt\layouts\partials\function\content.html:6:23": execute of template failed: template: partials/function/content.html:6:23: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.
```

**Comment by HEIGE-PCloud** [comment] 2021-07-04 07:58
I'm very sorry for closing this issue too quickly. I manage to reproduce this issue at `hugo v0.84.4`, it might relate to #40. I will look into it right now. Thank you very much for proposing this issue!

**Comment by zhaoyiluo** [comment] 2021-07-04 08:03
So much appreciate it. Take your time!

**Comment by HEIGE-PCloud** [comment] 2021-07-04 08:20
Check out the latest commit, it should fix the issue.

```
$ npm run serve

> hugo server --source=exampleSite --themesDir ../.. -D --disableFastRender

Start building sites … 
hugo v0.84.4-020E4ACE+extended windows/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
WARN 2021/07/04 16:19:05 

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.
WARN 2021/07/04 16:19:05 

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.

                   | EN  | ZH-CN | FR  
-------------------+-----+-------+-----
  Pages            | 107 |    45 | 36
  Paginator pages  |   1 |     0 |  0
  Non-page files   |  14 |    14 | 17
  Static files     |  94 |    94 | 94
  Processed images |   0 |     0 |  0
  Aliases          |  26 |    17 | 12
  Sitemaps         |   2 |     1 |  1
  Cleaned          |   0 |     0 |  0

Built in 1752 ms
Watching for changes in DoIt\{archetypes,assets,exampleSite,i18n,layouts,package.json,static}
Watching for config changes in exampleSite\config.toml
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by zhaoyiluo** [comment] 2021-07-04 08:51
Thanks for your fast fix but it still has some errors on my side.

Approach 1: run `hugo server --source=themes\DoIt\exampleSite --disableFastRender`, under `IMZLUO` folder
```
E:\IMZLUO>hugo server --source=themes/DoIt/exampleSite --disableFastRender
Start building sites …
hugo v0.84.4-020E4ACE+extended windows/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
WARN 2021/07/04 16:46:43

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
Built in 30471 ms
Error: Error building site: "E:\IMZLUO\themes\DoIt\exampleSite\content\posts\theme-documentation-built-in-shortcodes\index.en.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
```

Approach 2: run `npm run serve`, under `IMZLUO\themes\DoIt` folder
```
E:\IMZLUO\themes\DoIt>npm run serve

> doit-src@0.2.0 serve E:\IMZLUO\themes\DoIt
> hugo server --source=exampleSite --themesDir ../.. -D --disableFastRender

Start building sites …
hugo v0.84.4-020E4ACE+extended windows/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
WARN 2021/07/04 16:49:36

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
Built in 30551 ms
Error: Error building site: "E:\IMZLUO\themes\DoIt\exampleSite\content\posts\theme-documentation-built-in-shortcodes\index.en.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! doit-src@0.2.0 serve: `hugo server --source=exampleSite --themesDir ../.. -D --disableFastRender`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the doit-src@0.2.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ZhaoyiLuo\AppData\Roaming\npm-cache\_logs\2021-07-04T08_50_07_322Z-debug.log
```

**Comment by HEIGE-PCloud** [comment] 2021-07-04 08:57
The built-in shortcode `tweet` is causing problem again. The timeout is caused by failing in Twitter's API.

Remove the line `{{< tweet 877500564405444608 >}}` in the following 4 files and try build the site again.

1. `DoIt\exampleSite\content\posts\tests\builtin-shortcodes-tests\index.en.md` Line 48
2. `DoIt\exampleSite\content\posts\theme-documentation-built-in-shortcodes\index.en.md` Line 138
3. `DoIt\exampleSite\content\posts\theme-documentation-built-in-shortcodes\index.fr.md` Line 157
4. `DoIt\exampleSite\content\posts\theme-documentation-built-in-shortcodes\index.zh-cn.md` Line 139

If you remove `ignoreErrors = ["error-remote-getjson"]` in your config file, you should see the error log for Twitter.

**Comment by zhaoyiluo** [comment] 2021-07-04 09:24
The twitter ghost is really annoying.

I tried one more time on my company computer and all the issues related to Twitter disappeared (even no need to include `ignoreErrors = ["error-remote-getjson"]`).

Maybe I should transfer all my work from my personal laptop to avoid these unnecessary issues.

BTW, thanks for your timely fix and everything is set now!

**Closed as completed** 2021-07-04 09:25 UTC
Labels: bug
